name: GitHub Actions CI
on: [push]
jobs:
  tests:
    runs-on: macOS-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Bootstrap
      run: ./script/bootstrap

    - name: Cleanup macOS
      run: |
        sudo rm -rf /usr/local/bin/brew /usr/local/.??* \
                    /Applications/Xcode.app /usr/local/Caskroom \
                    /Library/Developer/CommandLineTools
        sudo pkgutil --forget com.apple.pkg.CLTools_Executables

    - name: Use newer Xcode
      run: sudo xcode-select --switch /Applications/Xcode_10.2.1.app/Contents/Developer

    - name: CI Tests
      run: ./script/cibuild
